# Generated by Django 5.2.7 on 2026-05-08 21:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0051_mercancia_estado_cobranza_and_more'),
        ('usuarios', '0007_alter_perfil_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('Factura', 'Factura Electrónica'), ('Guia_Cobro', 'Guía de Cobro (Sin Factura)')], default='Factura', max_length=20)),
                ('numero_documento', models.IntegerField(blank=True, null=True, verbose_name='Folio SII o N° Interno')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('condicion_pago', models.CharField(choices=[('Contra_Entrega', 'Contra Entrega'), ('Dias_15', '15 Días'), ('Dias_30', '30 Días'), ('Dias_45', '45 Días'), ('Dias_60', '60 Días')], default='Dias_30', max_length=20)),
                ('fecha_vencimiento', models.DateField(verbose_name='Vence el')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total_a_pagar', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('saldo_pendiente', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Monto por Pagar')),
                ('estado', models.CharField(choices=[('Emitido', 'Emitido (Por Pagar)'), ('Abonado', 'Abonado (Pago Parcial)'), ('Pagado', 'Pagado Totalmente'), ('Anulado', 'Anulado')], default='Emitido', max_length=20)),
                ('pdf_documento', models.FileField(blank=True, null=True, upload_to='cobranzas/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('cliente_deudor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='inventario.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_cobro', to='usuarios.empresa')),
                ('mercancias_asociadas', models.ManyToManyField(related_name='documentos_cobro_asociados', to='inventario.mercancia')),
                ('proveedor_deudor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='inventario.proveedor')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='GastoOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_gasto', models.CharField(choices=[('Combustible', 'Combustible'), ('Peaje', 'Peaje'), ('Mantenimiento', 'Mantenimiento / Taller'), ('Viatico', 'Viático de Conductor'), ('Servicio Externo', 'Flete Externo / Proveedor'), ('Administrativo', 'Gasto Administrativo')], max_length=50)),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción del Gasto')),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° Boleta/Factura')),
                ('fecha_gasto', models.DateField(default=django.utils.timezone.now)),
                ('monto_total', models.DecimalField(decimal_places=0, max_digits=12)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente de Pago'), ('Pagado', 'Pagado')], default='Pendiente', max_length=20)),
                ('comprobante_adjunto', models.FileField(blank=True, null=True, upload_to='comprobantes_gastos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('camion_asociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='inventario.camion')),
                ('conductor_asociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viaticos', to='inventario.conductor')),
                ('despacho_asociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_ruta', to='inventario.despacho')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='usuarios.empresa')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos_emitidos', to='inventario.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='PagoRecibido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha en el Banco')),
                ('monto_pagado', models.DecimalField(decimal_places=0, max_digits=12)),
                ('medio_pago', models.CharField(choices=[('Transferencia', 'Transferencia Bancaria'), ('Efectivo', 'Efectivo'), ('Cheque_Dia', 'Cheque al Día'), ('Cheque_Fecha', 'Cheque a Fecha')], default='Transferencia', max_length=20)),
                ('numero_operacion_banco', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Transferencia / Cheque')),
                ('comprobante_banco', models.FileField(blank=True, null=True, upload_to='comprobantes_banco/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('documento_pagado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='finanzas.documentocobro')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_recibidos', to='usuarios.empresa')),
            ],
        ),
    ]
