# Generated by Django 5.2.7 on 2026-05-20 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
        ('usuarios', '0007_alter_perfil_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=120, verbose_name='Nombre o Razón Social')),
                ('rut_proveedor', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='RUT Proveedor')),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores_gastos', to='usuarios.empresa')),
            ],
        ),
        migrations.AlterField(
            model_name='gastooperativo',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos_asociados', to='finanzas.proveedorgasto'),
        ),
    ]
