# Generated by Django 5.2.7 on 2025-10-24 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id_camion', models.AutoField(primary_key=True, serialize=False)),
                ('patente', models.CharField(max_length=10, unique=True, verbose_name='Patente')),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('capacidad_max_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Capacidad Máx (Kg)')),
                ('capacidad_max_m3', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Capacidad Máx (m³)')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=150, verbose_name='Nombre o Razón Social')),
                ('rut_cliente', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='RUT')),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email_contacto', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id_conductor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('rut_conductor', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('numero_licencia', models.CharField(max_length=20, verbose_name='N° Licencia')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
            ],
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id_destino', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ciudad', models.CharField(max_length=100, verbose_name='Nombre de Ciudad')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Región')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id_ruta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ruta', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Ruta')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_ubicacion', models.CharField(max_length=20, unique=True, verbose_name='Código de Ubicación')),
                ('pasillo', models.CharField(max_length=10)),
                ('estanteria', models.IntegerField()),
                ('nivel', models.IntegerField()),
                ('pos_x', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Posición X (para 3D)')),
                ('pos_y', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Posición Y (para 3D)')),
                ('pos_z', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Posición Z (para 3D)')),
                ('capacidad_max_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Capacidad Máx (Kg)')),
                ('capacidad_max_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Capacidad Máx (m³)')),
                ('estado_ocupado', models.BooleanField(default=False, verbose_name='Ocupado')),
            ],
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id_despacho', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_programada', models.DateField(verbose_name='Fecha Programada')),
                ('fecha_salida_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Salida Real')),
                ('estado_despacho', models.CharField(choices=[('Programado', 'Programado'), ('En Carga', 'En Carga'), ('En Tránsito', 'En Tránsito'), ('Finalizado', 'Finalizado')], default='Programado', max_length=20, verbose_name='Estado')),
                ('id_camion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.camion', verbose_name='Camión')),
                ('id_conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.conductor', verbose_name='Conductor')),
                ('id_usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creación')),
                ('id_usuario_ultima_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despachos_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación')),
                ('id_ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.ruta', verbose_name='Ruta')),
            ],
        ),
        migrations.CreateModel(
            name='Mercancia',
            fields=[
                ('id_mercancia', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_carga', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('cantidad_bultos', models.IntegerField(default=1, verbose_name='Cantidad de Bultos')),
                ('kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso (Kg)')),
                ('m3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Volumen (m³)')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('estado', models.CharField(choices=[('En Bodega', 'En Bodega'), ('Asignado', 'Asignado a Despacho'), ('En Tránsito', 'En Tránsito'), ('Entregado', 'Entregado')], default='En Bodega', max_length=20, verbose_name='Estado')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.cliente', verbose_name='Cliente')),
                ('id_despacho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.despacho', verbose_name='Despacho Asignado')),
                ('id_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.destino', verbose_name='Destino')),
                ('id_usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mercancias_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creación')),
                ('id_usuario_ultima_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mercancias_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificación')),
                ('id_ubicacion_actual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.ubicacion', verbose_name='Ubicación Actual')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('kg__isnull', False), ('m3__isnull', False), _connector='OR'), name='kg_o_m3_no_nulos')],
            },
        ),
    ]
