# Generated by Django 5.2.7 on 2025-10-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_despacho_id_usuario_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercancia',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
