# Generated by Django 5.2.7 on 2025-11-15 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_mercancia_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercancia',
            name='estado',
            field=models.CharField(choices=[('En Bodega', 'En Bodega'), ('Asignado', 'Asignado a Despacho'), ('En Tránsito', 'En Tránsito'), ('Entregado', 'Entregado'), ('Eliminado', 'Eliminado')], default='En Bodega', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='HistorialMovimientos',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_movimiento', models.DateTimeField(auto_now_add=True)),
                ('tipo_movimiento', models.CharField(choices=[('Creación', 'Creación'), ('Modificación Manual', 'Modificación Manual'), ('Asignación Despacho', 'Asignación Despacho'), ('Borrado Lógico', 'Borrado Lógico')], max_length=50)),
                ('descripcion_adicional', models.CharField(blank=True, max_length=255, null=True)),
                ('id_mercancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='inventario.mercancia')),
                ('id_ubicacion_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_anterior', to='inventario.ubicacion')),
                ('id_ubicacion_nueva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_nueva', to='inventario.ubicacion')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
