# Generated by Django 5.2.7 on 2025-11-17 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_camion_activo_cliente_activo_conductor_activo_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='camiones', to='usuarios.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='usuarios.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conductor',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conductores', to='usuarios.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='despacho',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='despachos', to='usuarios.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destino',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='usuarios.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialmovimientos',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='historial_movimientos', to='usuarios.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mercancia',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mercancias', to='usuarios.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ruta',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='usuarios.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='usuarios.empresa'),
            preserve_default=False,
        ),
    ]
