# Generated by Django 5.2.7 on 2025-11-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_camion_empresa_cliente_empresa_conductor_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
