# Generated by Django 5.2.7 on 2025-11-18 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_despacho_activo'),
        ('usuarios', '0002_perfil_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'verbose_name_plural': 'Ubicaciones'},
        ),
        migrations.AlterUniqueTogether(
            name='ubicacion',
            unique_together={('empresa', 'codigo_ubicacion')},
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='capacidad_maxima_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Capacidad Máxima (kg)'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='es_zona_suelo',
            field=models.BooleanField(default=False, verbose_name='¿Es zona de suelo?'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='pos_x_rel',
            field=models.IntegerField(default=0, verbose_name='Posición Relativa X (módulo)'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='pos_y_rel',
            field=models.IntegerField(default=0, verbose_name='Posición Relativa Y (nivel)'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='pos_z_rel',
            field=models.IntegerField(default=0, verbose_name='Posición Relativa Z (profundidad)'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='tipo_almacenamiento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Almacenamiento'),
        ),
        migrations.AlterField(
            model_name='mercancia',
            name='id_ubicacion_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mercancias_en_ubicacion', to='inventario.ubicacion'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='codigo_ubicacion',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código de Ubicación'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='estado_ocupado',
            field=models.BooleanField(default=False, verbose_name='Estado Ocupado'),
        ),
        migrations.CreateModel(
            name='Estanteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_estanteria', models.CharField(max_length=50, unique=True, verbose_name='Código de Estantería')),
                ('pos_x', models.FloatField(default=0.0, verbose_name='Posición X (m)')),
                ('pos_y', models.FloatField(default=0.0, verbose_name='Posición Y (m)')),
                ('pos_z', models.FloatField(default=0.0, verbose_name='Posición Z (m)')),
                ('num_modulos_ancho', models.IntegerField(default=1, verbose_name='Módulos de Ancho')),
                ('num_niveles_alto', models.IntegerField(default=1, verbose_name='Niveles de Alto')),
                ('num_profundidad', models.IntegerField(default=1, verbose_name='Espacios de Profundidad')),
                ('ancho_hueco_m', models.FloatField(default=1.0, verbose_name='Ancho de cada hueco (m)')),
                ('alto_hueco_m', models.FloatField(default=1.0, verbose_name='Alto de cada hueco (m)')),
                ('profundo_hueco_m', models.FloatField(default=1.0, verbose_name='Profundidad de cada hueco (m)')),
                ('is_active', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estanterias', to='usuarios.empresa')),
            ],
            options={
                'verbose_name_plural': 'Estanterías',
                'unique_together': {('empresa', 'codigo_estanteria')},
            },
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='estanteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicaciones_en_estanteria', to='inventario.estanteria'),
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='capacidad_max_kg',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='pasillo',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='pos_x',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='pos_y',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='pos_z',
        ),
    ]
