# Generated by Django 5.2.7 on 2025-11-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_ubicacion_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estanteria',
            old_name='is_active',
            new_name='activo',
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
