# Generated by Django 5.2.7 on 2025-11-26 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_reportegenerado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmovimientos',
            name='id_mercancia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='inventario.mercancia'),
        ),
    ]
