# Generated by Django 5.2.7 on 2025-11-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_alter_historialmovimientos_id_mercancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercancia',
            name='motivo_baja',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Baja/Merma'),
        ),
    ]
