# Generated by Django 5.2.7 on 2025-11-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_mercancia_motivo_baja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercancia',
            name='estado',
            field=models.CharField(choices=[('En Bodega', 'En Bodega'), ('Asignado', 'Asignado a Despacho'), ('En Tránsito', 'En Tránsito'), ('Entregado', 'Entregado'), ('Eliminado', 'Eliminado'), ('Merma', 'Merma')], default='En Bodega', max_length=20, verbose_name='Estado'),
        ),
    ]
