# Generated by Django 5.2.7 on 2025-11-27 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_alter_mercancia_estado'),
        ('usuarios', '0003_empresa_almacen_alto_empresa_almacen_ancho_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaRestringida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre (Ej: Oficina)')),
                ('pos_x', models.FloatField(verbose_name='Posición X (m)')),
                ('pos_z', models.FloatField(verbose_name='Posición Z (m)')),
                ('ancho', models.FloatField(verbose_name='Ancho (m)')),
                ('largo', models.FloatField(verbose_name='Largo (m)')),
                ('alto', models.FloatField(default=3.0, verbose_name='Alto (m)')),
                ('color', models.CharField(default='#ff0000', max_length=20, verbose_name='Color Hex')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_restringidas', to='usuarios.empresa')),
            ],
        ),
    ]
