# Generated by Django 5.2.7 on 2025-11-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_arearestringida'),
    ]

    operations = [
        migrations.AddField(
            model_name='arearestringida',
            name='rotacion',
            field=models.FloatField(default=0.0, verbose_name='Rotación (Grados)'),
        ),
        migrations.AddField(
            model_name='estanteria',
            name='rotacion',
            field=models.FloatField(default=0.0, verbose_name='Rotación (Grados)'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='rotacion',
            field=models.FloatField(default=0.0, verbose_name='Rotación (Grados)'),
        ),
    ]
