# Generated by Django 5.2.7 on 2025-11-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_arearestringida_rotacion_estanteria_rotacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estanteria',
            name='capacidad_carga_por_hueco_kg',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='Capacidad por Hueco (Kg)'),
        ),
    ]
