# Generated by Django 5.2.7 on 2025-12-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_estanteria_capacidad_carga_por_hueco_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='anio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='camion',
            name='estado_camion',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_USO', 'En Uso'), ('MANTENIMIENTO', 'Mantenimiento')], default='DISPONIBLE', max_length=20, verbose_name='Estado'),
        ),
    ]
