# Generated by Django 5.2.7 on 2025-12-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_camion_anio_camion_estado_camion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmovimientos',
            name='accion',
            field=models.CharField(default='Registro Antiguo', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialmovimientos',
            name='modelo_afectado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Módulo (Ej: Camión)'),
        ),
    ]
