# Generated by Django 5.2.7 on 2026-03-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_historialmovimientos_accion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='precio_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio por Kg'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='precio_m3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio por m3'),
        ),
        migrations.AddField(
            model_name='mercancia',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Precio Calculado'),
        ),
    ]
