# Generated by Django 5.2.7 on 2026-03-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_cliente_precio_kg_cliente_precio_m3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad o Comuna'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Calle y Número'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_contacto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Persona de Contacto'),
        ),
    ]
