# Generated by Django 5.2.7 on 2026-03-24 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_cliente_ciudad_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('rut', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='RUT del Proveedor')),
                ('nombre_proveedor', models.CharField(max_length=150, verbose_name='Nombre / Razón Social')),
                ('contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Persona de Contacto')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='mercancia',
            name='id_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mercancias', to='inventario.proveedor', verbose_name='Proveedor de Origen'),
        ),
    ]
