# Generated by Django 5.2.7 on 2026-03-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0021_proveedor_mercancia_id_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercancia',
            name='factura',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Factura'),
        ),
    ]
