# Generated by Django 5.2.7 on 2026-03-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0022_mercancia_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='destino',
            field=models.CharField(choices=[('Santiago', 'Santiago'), ('Iquique', 'Iquique'), ('Antofagasta', 'Antofagasta'), ('Copiapo', 'Copiapo'), ('Mejillones', 'Mejillones'), ('Tocopilla', 'Tocopilla')], default='Santiago', max_length=50),
        ),
        migrations.AddField(
            model_name='despacho',
            name='origen',
            field=models.CharField(choices=[('Santiago', 'Santiago'), ('Iquique', 'Iquique'), ('Antofagasta', 'Antofagasta'), ('Copiapo', 'Copiapo'), ('Mejillones', 'Mejillones'), ('Tocopilla', 'Tocopilla')], default='Santiago', max_length=50),
        ),
    ]
