# Generated by Django 5.2.7 on 2026-03-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_despacho_destino_despacho_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='destino',
            field=models.CharField(blank=True, choices=[('Santiago', 'Santiago'), ('Iquique', 'Iquique'), ('Antofagasta', 'Antofagasta'), ('Copiapo', 'Copiapo'), ('Mejillones', 'Mejillones'), ('Tocopilla', 'Tocopilla')], default='Santiago', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='origen',
            field=models.CharField(blank=True, choices=[('Santiago', 'Santiago'), ('Iquique', 'Iquique'), ('Antofagasta', 'Antofagasta'), ('Copiapo', 'Copiapo'), ('Mejillones', 'Mejillones'), ('Tocopilla', 'Tocopilla')], default='Santiago', max_length=50, null=True),
        ),
    ]
