# Generated by Django 5.2.7 on 2026-03-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0024_alter_despacho_destino_alter_despacho_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='codigo_documento',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
