# Generated by Django 5.2.7 on 2026-03-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0025_despacho_codigo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercancia',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de carga'),
        ),
    ]
