# Generated by Django 5.2.7 on 2026-03-26 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0026_mercancia_tipo'),
        ('usuarios', '0003_empresa_almacen_alto_empresa_almacen_ancho_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camion',
            name='capacidad_max_kg',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='capacidad_max_m3',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='precio_kg',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=10, verbose_name='Precio por Kg'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='precio_m3',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=10, verbose_name='Precio por m3'),
        ),
        migrations.AlterField(
            model_name='mercancia',
            name='kg',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Peso (Kg)'),
        ),
        migrations.AlterField(
            model_name='mercancia',
            name='precio_total',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=12, verbose_name='Precio Calculado'),
        ),
        migrations.CreateModel(
            name='Rampla',
            fields=[
                ('id_rampla', models.AutoField(primary_key=True, serialize=False)),
                ('patente', models.CharField(max_length=10, unique=True, verbose_name='Patente Rampla')),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('capacidad_max_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Capacidad Máx (Kg)')),
                ('capacidad_max_m3', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Capacidad Máx (m³)')),
                ('activo', models.BooleanField(default=True)),
                ('anio', models.IntegerField(blank=True, null=True, verbose_name='Año')),
                ('estado_rampla', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_USO', 'En Uso'), ('MANTENIMIENTO', 'Mantenimiento')], default='DISPONIBLE', max_length=20, verbose_name='Estado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ramplas', to='usuarios.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='despacho',
            name='id_rampla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachos', to='inventario.rampla'),
        ),
    ]
