# Generated by Django 5.2.7 on 2026-03-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0027_remove_camion_capacidad_max_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercancia',
            name='paga_proveedor',
            field=models.BooleanField(default=False, verbose_name='¿Paga Proveedor?'),
        ),
    ]
