# Generated by Django 5.2.7 on 2026-03-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0028_mercancia_paga_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercancia',
            name='codigo_interno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Interno Bodega'),
        ),
    ]
