# Generated by Django 5.2.7 on 2026-03-26 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0029_mercancia_codigo_interno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despacho',
            name='codigo_documento',
        ),
    ]
