# Generated by Django 5.2.7 on 2026-03-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0030_remove_despacho_codigo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercancia',
            name='kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso (Kg)'),
        ),
    ]
