# Generated by Django 5.2.7 on 2026-03-26 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0031_alter_mercancia_kg'),
        ('usuarios', '0004_sucursal_perfil_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='arearestringida',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.sucursal'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.sucursal'),
        ),
        migrations.AddField(
            model_name='destino',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.sucursal'),
        ),
        migrations.AddField(
            model_name='estanteria',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.sucursal'),
        ),
        migrations.AddField(
            model_name='historialmovimientos',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.sucursal'),
        ),
        migrations.AddField(
            model_name='mercancia',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.sucursal'),
        ),
        migrations.AddField(
            model_name='reportegenerado',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.sucursal'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.sucursal'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.sucursal'),
        ),
    ]
