# Generated by Django 5.2.7 on 2026-03-27 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0032_arearestringida_sucursal_despacho_sucursal_and_more'),
        ('usuarios', '0004_sucursal_perfil_sucursal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destino',
            name='sucursal',
        ),
        migrations.AlterField(
            model_name='arearestringida',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.sucursal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='despacho',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.sucursal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estanteria',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.sucursal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historialmovimientos',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.sucursal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mercancia',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.sucursal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportegenerado',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.sucursal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ruta',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.sucursal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.sucursal'),
            preserve_default=False,
        ),
    ]
