# Generated by Django 5.2.7 on 2026-03-27 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0033_remove_destino_sucursal_and_more'),
        ('usuarios', '0004_sucursal_perfil_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmovimientos',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.sucursal'),
        ),
    ]
