# Generated by Django 5.2.7 on 2026-03-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0034_alter_historialmovimientos_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercancia',
            name='numero_orden_entrega',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
