# Generated by Django 5.2.7 on 2026-03-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0035_mercancia_numero_orden_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='codigo_ruta',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de Ruta'),
        ),
    ]
