# Generated by Django 5.2.7 on 2026-03-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0036_ruta_codigo_ruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='codigo_ruta',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Código de Ruta'),
        ),
    ]
