# Generated by Django 5.2.7 on 2026-03-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0037_alter_ruta_codigo_ruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercancia',
            name='m3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Volumen (m³)'),
        ),
    ]
