# Generated by Django 5.2.7 on 2026-04-06 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0038_alter_mercancia_m3'),
        ('usuarios', '0005_empresa_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='usuarios.empresa'),
            preserve_default=False,
        ),
    ]
