# Generated by Django 5.2.7 on 2026-04-10 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0039_proveedor_empresa'),
        ('usuarios', '0005_empresa_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id_cotizacion', models.AutoField(primary_key=True, serialize=False)),
                ('rut_cliente', models.CharField(max_length=12, verbose_name='RUT cliente')),
                ('rut_proveedor', models.CharField(max_length=12, verbose_name='RUT proveedor')),
                ('nombre_cliente', models.CharField(max_length=150, verbose_name='Nombre o Razón Social')),
                ('proveedor', models.CharField(max_length=150, verbose_name='Nombre o Razón Social')),
                ('contacto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contacto cotización')),
                ('destino', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección de destino')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad de bultos')),
                ('tipo_bultos', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de bultos')),
                ('kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso (Kg)')),
                ('m3', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Volumen (m³)')),
                ('estado_cotizacion', models.CharField(choices=[('En proceso', 'En proceso'), ('Cotizado', 'Cotizado')], max_length=50)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha confirmación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('cotiza_proveedor', models.BooleanField(default=False, verbose_name='¿Cotiza proveedor?')),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='usuarios.empresa')),
                ('id_usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creación')),
            ],
        ),
    ]
