# Generated by Django 5.2.7 on 2026-04-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0040_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto Cotizado'),
        ),
    ]
