# Generated by Django 5.2.7 on 2026-04-15 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0042_permisocolaboracion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permisocolaboracion',
            options={'verbose_name': 'Permiso de Colaboración', 'verbose_name_plural': 'Permisos de Colaboración'},
        ),
        migrations.AlterField(
            model_name='permisocolaboracion',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si es False, el usuario pierde el acceso inmediatamente.'),
        ),
        migrations.AlterField(
            model_name='permisocolaboracion',
            name='otorgado_por',
            field=models.ForeignKey(help_text='El usuario (jefe/admin) que concedió este permiso.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitaciones_enviadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
