# Generated by Django 5.2.7 on 2026-04-16 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0043_alter_permisocolaboracion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SucursalCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_especifica', models.CharField(max_length=255)),
                ('ciudad_especifica', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales_destino', to='inventario.cliente')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.destino')),
            ],
            options={
                'unique_together': {('cliente', 'destino')},
            },
        ),
    ]
