# Generated by Django 5.2.7 on 2026-04-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0044_sucursalcliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ciudad2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad o Comuna (Secundaria)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Calle y Número (Secundaria)'),
        ),
        migrations.DeleteModel(
            name='SucursalCliente',
        ),
    ]
