# Generated by Django 5.2.7 on 2026-04-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0045_cliente_ciudad2_cliente_direccion2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='estado_despacho',
            field=models.CharField(choices=[('Programado', 'Programado'), ('En Carga', 'En Carga'), ('En Tránsito', 'En Tránsito'), ('Finalizado', 'Finalizado'), ('Eliminado', 'Eliminado')], default='Programado', max_length=20, verbose_name='Estado'),
        ),
    ]
