# Generated by Django 5.2.7 on 2026-04-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0046_alter_despacho_estado_despacho'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercancia',
            name='direccion_entrega',
            field=models.CharField(blank=True, help_text='Dirección específica de entrega para esta carga', max_length=255, null=True, verbose_name='Dirección de entrega'),
        ),
    ]
