# Generated by Django 5.2.7 on 2026-05-05 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0047_mercancia_direccion_entrega'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_invitacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores_invitados', to='inventario.cotizacion')),
                ('otorgado_por', models.ForeignKey(help_text='El usuario que concedió este permiso.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitaciones_cotizacion_enviadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_invitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones_compartidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso de Cotización',
                'verbose_name_plural': 'Permisos de Cotizaciones',
                'unique_together': {('cotizacion', 'usuario_invitado')},
            },
        ),
    ]
