# Generated by Django 5.2.7 on 2026-05-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0048_permisocotizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Monto Cotizado'),
        ),
    ]
