# Generated by Django 5.2.7 on 2026-05-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0049_alter_cotizacion_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmovimientos',
            name='detalles',
            field=models.JSONField(blank=True, help_text='Guarda una foto en formato JSON de los datos en ese momento.', null=True, verbose_name='Detalles del Movimiento'),
        ),
    ]
