# Generated by Django 5.2.7 on 2026-05-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0050_historialmovimientos_detalles'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercancia',
            name='estado_cobranza',
            field=models.CharField(choices=[('Pendiente', 'Pendiente de Cobro'), ('En_Proceso', 'En Proceso de Cobro (Facturado)'), ('Pagado', 'Pagado')], default='Pendiente', max_length=20, verbose_name='Estado de Cobranza'),
        ),
        migrations.AddField(
            model_name='mercancia',
            name='tipo_documento_pago',
            field=models.CharField(choices=[('Factura', 'Factura (+ IVA)'), ('Sin_Factura', 'Sin Factura / Guía')], default='Factura', max_length=20, verbose_name='Tipo de Cobro'),
        ),
    ]
