# Generated by Django 5.2.7 on 2026-06-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0051_mercancia_estado_cobranza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion_cifrado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_cifrado2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email_cifrado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rut_cliente_cifrado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono_cifrado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conductor',
            name='licencia_cifrado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conductor',
            name='rut_conductor_cifrado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conductor',
            name='telefono_conductor_cifrado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='correo_cifrado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono_cifrado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
