# Generated by Django 5.2.7 on 2026-06-01 14:32

from django.db import migrations
from cryptography.fernet import Fernet
from django.conf import settings


def cifrar_todo_lo_antiguo(apps, schema_editor):
    Cliente = apps.get_model('inventario', 'Cliente')
    Conductor = apps.get_model('inventario', 'Conductor')
    Proveedor = apps.get_model('inventario', 'Proveedor')
    
    fernet = Fernet(settings.FIELD_ENCRYPTION_KEY.encode())

    for c in Cliente.objects.all():
        if c.rut_cliente and not c.rut_cliente_cifrado:
            c.rut_cliente_cifrado = fernet.encrypt(c.rut_cliente.encode('utf-8')).decode('utf-8')
        if c.telefono_contacto and not c.telefono_cifrado:
            c.telefono_cifrado = fernet.encrypt(c.telefono_contacto.encode('utf-8')).decode('utf-8')
        if c.email_contacto and not c.email_cifrado:
            c.email_cifrado = fernet.encrypt(c.email_contacto.encode('utf-8')).decode('utf-8')
        if c.direccion and not c.direccion_cifrado:
            c.direccion_cifrado = fernet.encrypt(c.direccion.encode('utf-8')).decode('utf-8')
        if c.direccion2 and not c.direccion_cifrado2:
            c.direccion_cifrado2 = fernet.encrypt(c.direccion2.encode('utf-8')).decode('utf-8')
        c.save()

    for cond in Conductor.objects.all():
        if cond.rut_conductor and not cond.rut_conductor_cifrado:
            cond.rut_conductor_cifrado = fernet.encrypt(cond.rut_conductor.encode('utf-8')).decode('utf-8')
        if cond.telefono and not cond.telefono_conductor_cifrado:
            cond.telefono_conductor_cifrado = fernet.encrypt(cond.telefono.encode('utf-8')).decode('utf-8')
        if cond.numero_licencia and not cond.licencia_cifrado:
            cond.licencia_cifrado = fernet.encrypt(cond.numero_licencia.encode('utf-8')).decode('utf-8')
        cond.save()

    for p in Proveedor.objects.all():
        if p.correo and not p.correo_cifrado:
            p.correo_cifrado = fernet.encrypt(p.correo.encode('utf-8')).decode('utf-8')
        if p.telefono and not p.telefono_cifrado:
            p.telefono_cifrado = fernet.encrypt(p.telefono.encode('utf-8')).decode('utf-8')
        p.save()

class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0052_cliente_direccion_cifrado_cliente_direccion_cifrado2_and_more'),
    ]

    operations = [
    ]
