# Generated by Django 5.2.7 on 2026-06-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0053_auto_20260601_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercancia',
            name='id_proveedor_nuevo_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='id_proveedor_nuevo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='rut_cifrado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
