# Generated by Django 5.2.7 on 2026-06-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0054_mercancia_id_proveedor_nuevo_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='direccion2',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email_contacto',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='rut_cliente',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono_contacto',
        ),
        migrations.RemoveField(
            model_name='conductor',
            name='numero_licencia',
        ),
        migrations.RemoveField(
            model_name='conductor',
            name='rut_conductor',
        ),
        migrations.RemoveField(
            model_name='conductor',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='mercancia',
            name='id_proveedor_nuevo_id',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='id_proveedor_nuevo',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='rut',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='telefono',
        ),
        migrations.AddField(
            model_name='cliente',
            name='rut_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='rut_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion_cifrado',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección Cifrada'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion_cifrado2',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección Cifrada2'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email_cifrado',
            field=models.TextField(blank=True, null=True, verbose_name='Email Cifrado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut_cliente_cifrado',
            field=models.TextField(blank=True, null=True, verbose_name='RUT Cifrado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono_cifrado',
            field=models.TextField(blank=True, null=True, verbose_name='Teléfono Cifrado'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='licencia_cifrado',
            field=models.TextField(blank=True, null=True, verbose_name='Licencia Cifrada'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='rut_conductor_cifrado',
            field=models.TextField(blank=True, null=True, verbose_name='RUT Cifrado'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='telefono_conductor_cifrado',
            field=models.TextField(blank=True, null=True, verbose_name='Teléfono Cifrado'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rut_cifrado',
            field=models.TextField(blank=True, null=True, verbose_name='RUT Cifrado'),
        ),
    ]
