# Generated by Django 5.2.7 on 2026-06-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0055_remove_cliente_direccion_remove_cliente_direccion2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='rut_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rut_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
