# Generated by Django 5.2.7 on 2026-06-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0056_conductor_rut_hash_alter_cliente_rut_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='rut_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rut_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
