# Generated by Django 5.2.7 on 2026-06-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0057_alter_cliente_rut_hash_alter_conductor_rut_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='orden_mercancias',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
