# Generated by Django 5.2.7 on 2026-07-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0058_despacho_orden_mercancias'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercancia',
            name='tipo_documento_mercancia',
            field=models.CharField(choices=[('Factura', 'Factura Electrónica'), ('Boleta', 'Boleta'), ('Guia', 'Guía de Despacho'), ('DUS', 'Documento Único de Salida (Aduana)'), ('Otros', 'Otros / Sin Documento')], default='Factura', max_length=30, verbose_name='Tipo de Documento de Mercancía'),
        ),
    ]
