# Generated by Django 5.2.7 on 2026-08-11 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0060_alter_mercancia_tipo_documento_mercancia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercancia',
            name='estado',
            field=models.CharField(choices=[('En Bodega', 'En Bodega'), ('Asignado', 'Asignado a Despacho'), ('En Tránsito', 'En Tránsito'), ('En Observacion', 'En Observación'), ('Entregado', 'Entregado'), ('Eliminado', 'Eliminado'), ('Merma', 'Merma')], default='En Bodega', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='RecepcionPatio',
            fields=[
                ('id_recepcion', models.AutoField(primary_key=True, serialize=False)),
                ('bultos_declarados', models.IntegerField(verbose_name='Bultos Declarados')),
                ('kg_declarados', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kg Declarados')),
                ('m3_declarados', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='m³ Declarados')),
                ('tipo_declarado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo Declarado')),
                ('bultos_recibidos', models.IntegerField(verbose_name='Bultos Recibidos')),
                ('kg_recibidos', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kg Recibidos')),
                ('m3_recibidos', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='m³ Recibidos')),
                ('tipo_recibido', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo Recibido')),
                ('conforme', models.BooleanField(default=True, verbose_name='¿Recepción Conforme?')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observaciones / Novedades')),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepciones_patio', to='inventario.despacho')),
                ('mercancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_recepciones', to='inventario.mercancia')),
                ('usuario_patio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Operador de Patio')),
            ],
            options={
                'verbose_name': 'Recepción de Patio',
                'verbose_name_plural': 'Recepciones de Patio',
            },
        ),
    ]
