# Generated by Django 5.2.7 on 2026-08-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0061_alter_mercancia_estado_recepcionpatio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercancia',
            name='estado',
            field=models.CharField(choices=[('En Bodega', 'En Bodega'), ('Asignado', 'Asignado a Despacho'), ('En Tránsito', 'En Tránsito'), ('En Observacion', 'En Observación'), ('Entregado', 'Entregado'), ('Recibido', 'Recibido'), ('Eliminado', 'Eliminado'), ('Merma', 'Merma')], default='En Bodega', max_length=20, verbose_name='Estado'),
        ),
    ]
