# Generated by Django 5.2.7 on 2026-09-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0062_alter_mercancia_estado'),
        ('usuarios', '0011_personaloperativo_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='codigo_ruta',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='ruta',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('sucursal', 'codigo_ruta'), name='unique_ruta_por_sucursal_activa'),
        ),
    ]
