# Generated by Django 5.2.7 on 2026-09-07 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0064_alter_recepcionpatio_usuario_patio'),
        ('usuarios', '0011_personaloperativo_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcionpatio',
            name='operativo_patio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones_patio', to='usuarios.personaloperativo'),
        ),
        migrations.AlterField(
            model_name='recepcionpatio',
            name='usuario_patio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones_patio', to=settings.AUTH_USER_MODEL),
        ),
    ]
