# Generated by Django 5.2.7 on 2026-07-21 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0060_alter_mercancia_tipo_documento_mercancia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_entrega', models.CharField(choices=[('Pendiente', 'Pendiente en Camión'), ('Entregado', 'Entregado Exitosamente'), ('Rechazado', 'Rechazado por Cliente'), ('No_Domicilio', 'No se encontraba en domicilio')], default='Pendiente', max_length=20)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('latitud_entrega', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud_entrega', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('foto_comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes_entrega/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('mercancia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='control_entrega', to='inventario.mercancia', verbose_name='Mercancía')),
            ],
            options={
                'verbose_name': 'Evidencia de Entrega (POD)',
                'verbose_name_plural': 'Evidencias de Entregas (POD)',
            },
        ),
        migrations.CreateModel(
            name='PerfilRepartidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('conductor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventario.conductor', verbose_name='Conductor ERP')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_movil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Repartidor Móvil',
                'verbose_name_plural': 'Perfiles de Repartidores Móviles',
            },
        ),
    ]
