# Generated by Django 5.2.7 on 2026-07-27 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0060_alter_mercancia_tipo_documento_mercancia'),
        ('seguiminto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteEntrega',
            fields=[
                ('id_comprobante', models.AutoField(primary_key=True, serialize=False)),
                ('url_archivo', models.URLField(max_length=500, verbose_name='URL del Comprobante')),
                ('nombre_original', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('despacho', models.ForeignKey(db_column='id_despacho', on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='inventario.despacho', verbose_name='Despacho')),
                ('mercancia', models.ForeignKey(db_column='id_mercancia', on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='inventario.mercancia', verbose_name='Mercancía')),
            ],
            options={
                'db_table': 'comprobante_entrega',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
