# Generated by Django 5.2.7 on 2025-11-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='rol',
            field=models.CharField(blank=True, choices=[('DUENO', 'Dueño'), ('SECRETARIA', 'Secretaria'), ('JEFE_BODEGA', 'Jefe de Bodega'), ('OPERARIO', 'Operario')], max_length=20, null=True, verbose_name='Rol en la Empresa'),
        ),
    ]
