# Generated by Django 5.2.7 on 2025-11-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='almacen_alto',
            field=models.FloatField(default=10.0, verbose_name='Alto Almacén (m)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='almacen_ancho',
            field=models.FloatField(default=20.0, verbose_name='Ancho Almacén (m)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='almacen_largo',
            field=models.FloatField(default=20.0, verbose_name='Largo Almacén (m)'),
        ),
    ]
