# Generated by Django 5.2.7 on 2026-03-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_sucursal_perfil_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo_empresas/', verbose_name='Logo de la empresa'),
        ),
    ]
