# Generated by Django 5.2.7 on 2026-05-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_perfil_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(blank=True, choices=[('DUENO', 'Dueño'), ('ADMINISTRATIVO', 'Administrativo'), ('SECRETARIA', 'Secretaria'), ('JEFE_BODEGA', 'Jefe de Bodega'), ('OPERARIO', 'Operario')], max_length=20, null=True, verbose_name='Rol en la Empresa'),
        ),
    ]
