# Generated by Django 5.2.7 on 2026-06-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_perfil_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False, verbose_name='2FA Activado'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Secreto TOTP'),
        ),
    ]
