# Generated by Django 5.2.7 on 2026-06-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_perfil_is_2fa_enabled_perfil_two_factor_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Secreto TOTP'),
        ),
    ]
