# Generated by Django 5.2.7 on 2026-08-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_perfil_two_factor_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_cifrado', models.TextField(verbose_name='RUT Cifrado')),
                ('rut_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Hash RUT')),
                ('telefono_cifrado', models.TextField(verbose_name='Teléfono Cifrado')),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('PATIO', 'Bodeguero de Patio'), ('CHOFER', 'Conductor de Reparto')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Personal Operativo',
                'verbose_name_plural': 'Personal Operativo',
            },
        ),
    ]
