# Generated by Django 5.2.7 on 2026-08-14 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_personaloperativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaloperativo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_operativo', to='usuarios.empresa'),
        ),
    ]
